kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: configure-goalert-operator
rules:
- apiGroups:
  - goalert.managed.openshift.io
  resources:
  - goalertintegrations
  - goalertintegrations/status
  - goalertintegrations/finalizers
  verbs:
  - get
  - list
  - watch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - hive.openshift.io
  attributeRestrictions: null
  resources:
  - clusterdeployments
  - clusterdeployments/finalizers
  - clusterdeployments/status
  - syncsets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - hive.openshift.io
  resources:
  - syncsets
  verbs:
  - create
  - delete
- apiGroups:
  - route.openshift.io
  resources:
  - routes
  verbs:
  - '*'
