apiVersion: v1
kind: Service
metadata:
  labels:
    name: configure-goalert-operator
  name: configure-goalert-operator-metrics
  namespace: configure-goalert-operator-operator
spec:
  selector:
    name: configure-goalert-operator
  ports:
    - name: metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
