apiVersion: apps/v1
kind: Deployment
metadata:
  name: configure-goalert-operator
  namespace: configure-goalert-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: configure-goalert-operator
  template:
    metadata:
      labels:
        name: configure-goalert-operator
    spec:
      serviceAccountName: configure-goalert-operator
      containers:
        - name: configure-goalert-operator
          image: <IMAGE_TAG>
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "2G"
              cpu: "100m"
            limits:
              memory: "2G"
              cpu: "100m"
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "configure-goalert-operator"
